

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SwapChainBackgroundPanel;
                ref class Grid;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualStateGroup;
            ref class VisualState;
        }
    }
}

namespace _2D_Game_Engine
{
    partial ref class DirectXPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::SwapChainBackgroundPanel^ DXSwapChainPanel;
        private: ::Windows::UI::Xaml::VisualStateGroup^ GameInfoOverlayStates;
        private: ::Windows::UI::Xaml::VisualState^ NormalState;
        private: ::Windows::UI::Xaml::VisualState^ GameInfoOverlayState;
        private: ::Windows::UI::Xaml::VisualState^ SnappedState;
        private: ::Windows::UI::Xaml::VisualState^ UnsnappedState;
        private: ::Windows::UI::Xaml::Controls::Grid^ GameInfoOverlay;
        private: ::Windows::UI::Xaml::Controls::Grid^ pauseButton;
    };
}

